### ISSUE TITLE
multiple countermeasures values in Docker not possible

### ISSUE THREAD

**Issue by r2ixuz** [commonshost/dohnut#22]
Setting both spoof-queries and spoof-useragent in docker-compose as environment variable does not work. Only one can specified.

Is it even possible to use both options?

**Comment by qoelet** [comment]
That wouldn't be possible in this scenario (assuming you're specifying multiple entries) because environment variables in docker-compose are read as strings/numbers/null, so if you're specifying multiple instances of `DOHNUT_COUNTERMEASURES` only the last one will be passed along.

If however you're doing `DOHNUT_COUNTERMEASURES=spoof-queries spoof-useragent` I would have expected that to work, but it seems like that is currently an [open issue mentioned in yargs](https://github.com/yargs/yargs/issues/821) (which is what Dohnut uses to parse options)

**Comment by r2ixuz** [comment]
Ok but setting multiple `DOHNUT_DOH=xxx yyy zzz` works as excepted. Even if you use URLs and not the shortnames. So why it cannot be parsed the same way for `DOHNUT_COUNTERMEASURES` ?

Yes, I tried with `DOHNUT_COUNTERMEASURES=spoof-queries spoof-useragent` which throws an error something like I have the "choice" between one of them. But in the PiHole doc example there are both options in one line. So my question is still also: Is it even possible to use both or do I have to pick `spoof-queries` OR `spoof-useragent`?

**Comment by qoelet** [comment]
It is possible to set both passing options twice, (to answer your question on whether both are possible)

```bash
$ docker run --net=host commonshost/dohnut --listen 0.0.0.0:53 --doh commonshost --bootstrap 1.1.1.1 --test --test --countermeasures spoof-queries --countermeasures spoof-useragent
Configuration is valid
{
  dns: [ { address: '0.0.0.0', type: 'udp4', port: 53 } ],
  doh: [ { uri: 'https://commons.host' } ],
  loadBalance: 'performance',
  countermeasures: [ 'spoof-queries', 'spoof-useragent' ],
  bootstrap: [ '1.1.1.1' ],
  datagramProtocol: 'udp6'
}
```

But not running  from docker-compose passing environment variables at this point. I suppose we can either wait for this to be resolved in yargs or open a PR for a workaround.

cc @sebdeckers

**Comment by qoelet** [comment]
There's actually a workaround for the yargs issue (https://github.com/commonshost/dohnut/blob/master/source/cli.js#L9) but it doesn't work probably due to the `choices` constraint (which comes before the workaround). As a temporary workaround, removing that works for me when tested locally.

**Comment by sebdeckers** [comment]
The patch seems to work (on my machine<sup>™️</sup>). Would appreciate a second look.

```yaml
version: "3"

services:
  dohnut:
    container_name: dohnut
    # image: commonshost/dohnut:latest
    build: .
    environment:
      TZ: "Europe/Brussels"
      DOHNUT_LISTEN: 127.0.0.1:8889
      DOHNUT_BOOTSTRAP: 1.1.1.1
      DOHNUT_DOH: commonshost cloudflare google
      DOHNUT_COUNTERMEASURES: spoof-queries spoof-useragent
      DOHNUT_TEST: "true"
    network_mode: "host"
```

```shell
$ docker-compose up
Starting dohnut ... done
Attaching to dohnut
dohnut    | Configuration is valid
dohnut    | {
dohnut    |   dns: [ { address: '127.0.0.1', type: 'udp4', port: 8889 } ],
dohnut    |   doh: [
dohnut    |     { uri: 'https://commons.host' },
dohnut    |     { uri: 'https://cloudflare-dns.com/dns-query' },
dohnut    |     { uri: 'https://dns.google/dns-query' }
dohnut    |   ],
dohnut    |   loadBalance: 'performance',
dohnut    |   countermeasures: [ 'spoof-queries', 'spoof-useragent' ],
dohnut    |   bootstrap: [ '1.1.1.1' ],
dohnut    |   datagramProtocol: 'udp6'
dohnut    | }
dohnut exited with code 0
```
